create table livro (liv_id int8 generated by default as identity, 
					liv_nome varchar(255), 
                    liv_datalancamento date, 
                    edit_id int8, 
                    sit_id int8, 
                    livt_id int8, 
                    primary key (liv_id));
